### PR TITLE
fix(eslint): emit plugin types correctly

### LINKED ISSUE #5133: `eslint-plugin-formatjs` does not export any types in its `index.d.ts`
## Which package?

`eslint-plugin-formatjs`

## Describe the bug

`eslint-plugin-formatjs` does not export any types in its `index.d.ts` on [npm](https://cdn.jsdelivr.net/npm/eslint-plugin-formatjs@5.4.2/index.d.ts).

This makes `eslint.config.mjs` typecheck fail when `formatjs.configs.recommended` is used since `configs`'s type is not declared.

### Codesandbox URL

[CodeSandbox link](https://codesandbox.io/p/devbox/eslint-formatjs-typescript-gd7jx8)

### Reproducible Steps/Repo

1. Setup a `@ts-check`'ed eslint config as [this](https://typescript-eslint.io/getting-started/#quickstart).
2. Add `formatjs.configs.recommended` to exported configs.

After that, `eslint.config.mjs` will look like this:

```js
// @ts-check

import eslint from "@eslint/js";
import { defineConfig } from "eslint/config";
import tseslint from "typescript-eslint";
import formatjs from "eslint-plugin-formatjs";

export default defineConfig(
  eslint.configs.recommended,
  tseslint.configs.recommended,
  formatjs.configs.recommended
);
```

If TypeScript is set up in the editor, `config` in `formatjs.configs.recommended` will be highlighted with error message:

> Property 'configs' does not exist on type `<module-path>`

If you jump to `formatjs` definition, it will open the [`index.d.ts`](https://cdn.jsdelivr.net/npm/eslint-plugin-formatjs@5.4.2/index.d.ts) file with just a single `export {}` declaration.

## Expected behavior

The config file will pass the type check without error or any `@ts-ignore` comments. That is said, `eslint-plugin-formatjs` should ship with a correct `index.d.ts` file.

## Screenshots

Screenshot

## Desktop (please complete the following information):

- OS: Windows 11
- Browser: Irrelevant
- Version: eslint-plugin-formatjs@5.4.2, eslint@9.37.0, typescript@5.9.3

## Additional context

Notify me if anything is needed.

### PR DESCRIPTION
**Pull request by sushichan044**
fixes #5133 

Since `index.ts` was using `module.exports`, the generated type definition file did not contain the correct contents.

This PR fixes the issue so that the type definition file is generated correctly and explicitly adds the `types` field to the package.json.

### CODE REVIEW

File: packages/eslint-plugin-formatjs/index.ts [hunk 1]
```diff
@@ -197,4 +211,4 @@ const configs: ESLint.Plugin['configs'] = {
 }
 plugin.configs = configs
```
Comment (sushichan044) [inline packages/eslint-plugin-formatjs/index.ts:212]: This is not directly related, but in this part, using `Object.assign` is recommended.
Ref: https://eslint.org/docs/latest/extend/plugin-migration-flat-config#migrating-configs-for-flat-config

**Review by longlho — APPROVED** [review]

**Comment by longlho** [comment]
Thanks a lot for your contributions!

**Comment by loganzartman** [comment]
hey @longlho, looks like CI checks got stuck. Could you merge and release this? I'd love to have the typedefs!

**Review by longlho — APPROVED** [review]
